// Bundle src/index.ts into one minified ESM file with zero runtime deps (only
// node: builtins stay external) and write it next to the Go embed:
//   ../plexus-bridge.min.mjs   the artifact (go:embed in install.go)
//   ../plexus-bridge.sha256    sha256sum-format manifest: the artifact, then
//                              every build input (checked by go test)
//
// Usage (from this directory, after `npm ci`):
//   node scripts/build.mjs           rebuild and rewrite both files
//   node scripts/build.mjs --check   rebuild to a scratch file; exit 1 unless it
//                                    is byte-identical to the committed artifact
//                                    and the manifest matches the inputs
//
// The bundler is Bun, pinned in package.json devDependencies and installed by
// `npm ci` (node_modules/bun). The build refuses to run with any other Bun, so
// the output is reproducible byte for byte. Nothing machine-specific (paths,
// times) goes into the artifact.
import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { gzipSync } from 'node:zlib'
import { createHash } from 'node:crypto'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const check = process.argv.includes('--check')
const here = dirname(dirname(fileURLToPath(import.meta.url))) // .../bridge/plugin
const bridge = dirname(here) // .../bridge
const pkg = JSON.parse(readFileSync(join(here, 'package.json'), 'utf8'))
const ARTIFACT = 'plexus-bridge.min.mjs'
const MANIFEST = 'plexus-bridge.sha256'
const sha = (b) => createHash('sha256').update(b).digest('hex')

// The pinned bundler, from node_modules (never whatever bun is on PATH).
const bunBin = join(here, 'node_modules', 'bun', 'bin', 'bun.exe') // the npm package's binary name on every OS
if (!existsSync(bunBin)) throw new Error(`pinned bun not installed (${bunBin}); run \`npm ci\` in ${here}`)
const want = pkg.devDependencies.bun
const got = execFileSync(bunBin, ['--version'], { encoding: 'utf8' }).trim()
if (got !== want) throw new Error(`bun ${got} != pinned ${want}; run \`npm ci\``)

const scratch = join(here, '.build')
rmSync(scratch, { recursive: true, force: true })
mkdirSync(scratch, { recursive: true })
const out = join(scratch, ARTIFACT)
execFileSync(bunBin, [
  'build', 'src/index.ts', // relative: no absolute path can reach the output
  '--target=node', '--format=esm', '--minify', '--packages=external',
  `--define=__PLEXUS_BRIDGE_VERSION__="${pkg.version}"`,
  '--outfile', out,
], { stdio: 'inherit', cwd: here })

let code = readFileSync(out, 'utf8')
rmSync(scratch, { recursive: true, force: true })
// Static imports (statement position), dynamic import() and require() of anything but node: builtins.
const importRe = /(?:^|[;}\n])\s*(?:import|export)\s*(?:[\w$*{][^;'"]*?from\s*)?["'](?!node:)|\bimport\(\s*["'](?!node:)|\brequire\(\s*["'](?!node:)/
if (importRe.test(code)) {
  throw new Error('bundle imports a non-builtin module; the artifact must have zero runtime deps')
}
const banner = `// ${pkg.name} ${pkg.version} (Plexus bridge protocol 1) - MIT. Generated by plugin/scripts/build.mjs; do not edit.\n`
const artifact = Buffer.from(banner + code.replace(/^\/\/ @bun\n/, ''), 'utf8')

// Every file that determines the artifact, in a fixed order, paths relative to bridge/.
const inputs = ['package.json', 'package-lock.json', 'tsconfig.json', 'scripts/build.mjs',
  ...readdirSync(join(here, 'src')).filter(f => f.endsWith('.ts')).sort().map(f => `src/${f}`)]
const manifest = [`${sha(artifact)}  ${ARTIFACT}`,
  ...inputs.map(f => `${sha(readFileSync(join(here, f)))}  plugin/${f}`)].join('\n') + '\n'

const info = { artifact: ARTIFACT, bytes: artifact.length, gzip_bytes: gzipSync(artifact, { level: 9 }).length, sha256: sha(artifact), version: pkg.version, bun: got }
if (check) {
  const committed = readFileSync(join(bridge, ARTIFACT))
  const committedManifest = readFileSync(join(bridge, MANIFEST), 'utf8')
  const ok = committed.equals(artifact) && committedManifest === manifest
  console.log(JSON.stringify({ ...info, committed_sha256: sha(committed), artifact_identical: committed.equals(artifact), manifest_identical: committedManifest === manifest }))
  process.exit(ok ? 0 : 1)
}
writeFileSync(join(bridge, ARTIFACT), artifact)
writeFileSync(join(bridge, MANIFEST), manifest)
console.log(JSON.stringify(info))
